### ISSUE TITLE
Program reports violations for `data_object_set.was_generated_by` references

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/refscan#5]
Here is a single example.

Excerpt from `violations.tsv`:

|source_collection_name|source_field_name|source_document_object_id|source_document_id    |target_id                  |
|----------------------|-----------------|-------------------------|----------------------|---------------------------|
|data_object_set       |was_generated_by |649b00451ae706d7b5b1a5f1 |nmdc:dobj-13-xx781m34 |nmdc:omprc-13-4wkf0639     |

Excerpt from `references.tsv`:

|source_collection_name|source_class_name|source_field_name|target_collection_name|target_class_name          |
|----------------------|-----------------|-----------------|----------------------|---------------------------|
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|MetatranscriptomeAnalysis  |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|MetatranscriptomeAssembly  |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|MetagenomeSequencing       |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|MetagenomeAnnotation       |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|ReadQcAnalysis             |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|MetatranscriptomeAnnotation|
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|WorkflowExecution          |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|MetagenomeAssembly         |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|MagsAnalysis               |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|NomAnalysis                |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|ReadBasedTaxonomyAnalysis  |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|MetaproteomicsAnalysis     |
|data_object_set       |DataObject       |was_generated_by |workflow_execution_set|MetabolomicsAnalysis       |

One of my teammates that is very familiar with the schema and database thinks this result is erroneous.

#### Configuration

- Schema (permalink): https://github.com/microbiomedata/berkeley-schema-fy24/blob/5ad80208ac78b4f18a7d03e6041e9da95a94a234/nmdc_schema/nmdc_materialized_patterns.yaml

```sh
# Download the raw content of https://github.com/microbiomedata/berkeley-schema-fy24/blob/main/nmdc_schema/nmdc_materialized_patterns.yaml
curl -o schema.yaml https://raw.githubusercontent.com/microbiomedata/berkeley-schema-fy24/main/nmdc_schema/nmdc_materialized_patterns.yaml
```

- Database: Mongo in Berkeley environment as of 1:15pm PT on Thursday, July 18, 2024

#### Tasks

- [x] Fully characterize the result (check the schema, database, etc.)
- [x] Identify the root cause of the issue
- [ ] Fix the issue (if local) or report the issue (if upstream)

**Comment by eecavanna** [comment]
Excerpts from the schema (with unrelated parts replaced with `# ...` here):

Slot [definition](https://github.com/microbiomedata/berkeley-schema-fy24/blob/5ad80208ac78b4f18a7d03e6041e9da95a94a234/nmdc_schema/nmdc_materialized_patterns.yaml#L16820C1-L16825C29):

```yaml
slots:
  # ...
  was_generated_by:
    name: was_generated_by
    from_schema: https://w3id.org/nmdc/nmdc
    mappings:
    - prov:wasGeneratedBy
    range: WorkflowExecution
```

Class [definition](https://github.com/microbiomedata/berkeley-schema-fy24/blob/5ad80208ac78b4f18a7d03e6041e9da95a94a234/nmdc_schema/nmdc_materialized_patterns.yaml#L21338-L21374C5):

```yaml
  DataObject:
    name: DataObject
    # ...
    slots:
    # ...
    - was_generated_by
    slot_usage:
      # ...
      was_generated_by:
        name: was_generated_by
        pattern: ^^(nmdc):(wfmag|wfmb|wfmgan|wfmgas|wfmsa|wfmp|wfmt|wfmtan|wfmtas|wfnom|wfrbt|wfrqc)-([0-9][a-z]{0,6}[0-9])-([A-Za-z0-9]{1,})(\.[0-9]{1,})$|^^(nmdc):(omprc|dgms|dgns)-([0-9][a-z]{0,6}[0-9])-([A-Za-z0-9]{1,})$
        structured_pattern:
          syntax: ^{id_nmdc_prefix}:(wfmag|wfmb|wfmgan|wfmgas|wfmsa|wfmp|wfmt|wfmtan|wfmtas|wfnom|wfrbt|wfrqc)-{id_shoulder}-{id_blade}{id_version}$|^{id_nmdc_prefix}:(omprc|dgms|dgns)-{id_shoulder}-{id_blade}$
          interpolated: true
    class_uri: nmdc:DataObject

```

**Comment by eecavanna** [comment]
Here's a `curl` command that can be used to find (via the [Berkeley Runtime API](https://api-berkeley.microbiomedata.org/docs#/metadata/get_by_id_nmdcschema_ids__doc_id__get)) the document being _referred_ to.

```shell
curl -X 'GET' \
  'https://api-berkeley.microbiomedata.org/nmdcschema/ids/nmdc%3Aomprc-13-4wkf0639' \
  -H 'accept: application/json'
```

**Comment by eecavanna** [comment]
I think my teammate expected `refscan` to have searched the `data_generation_set` collection. It isn't clear to me how the schema says that `DataObject.was_generated_by` can refer to something in a collection named `data_generation_set`.

**Comment by eecavanna** [comment]
Turns out this particular violation (and presumably others, although I haven't confirmed it) is due to [this bug](https://github.com/microbiomedata/nmdc-schema/issues/2134) in the `berkeley-schema-fy24` schema.

**Comment by eecavanna** [comment]
Now that the missing `any_of` constraint has been added to the Berkeley schema, I'll re-run refscan and check whether it still finds these violations.

**Comment by eecavanna** [comment]
Progress is blocked by the absence of the necessary YAML-formatted schema file in the `berkeley-schema-fy24` repo. I created a ticket about that, here: https://github.com/microbiomedata/nmdc-schema/issues/2150

**Comment by aclum** [comment]
Is this still blocked? the linked blocker was resolved in Aug.

**Comment by aclum** [comment]
this impacts violation reports for berkeley.

**Comment by eecavanna** [comment]
It's not blocked anymore. I'll update the issue title.

**Comment by eecavanna** [comment]
A scan of the Mongo database in the Spin-hosted development environment (using `nmdc-schema` version 11.0.1) reported 1819 violations involving `data_object_set.was_generated_by`. In all cases, the document having the referenced `id` existed in the `data_generation_set` collection. The reason refscan didn't look for them there is:

1. The schema says that, if the `was_generated_by` slot (of a `DataObject` instance) contains a value, that value must be the `id` of a document representing a `WorkflowExecution` instance.
   ![image](https://github.com/user-attachments/assets/ad1b6c08-98b4-44a3-a10b-e905cfc468dc)
2. The schema says the `data_generation_set` collection, if nonempty, must contain documents representing instances of the `DataGeneration` class.
   ![image](https://github.com/user-attachments/assets/6fc64c6d-7add-4303-9ae5-9e16177afeff)
3. The schema does not list the `DataGeneration` class as an ancestor of the `WorkflowExecution` class; rather, it lists them as siblings.
   ![image](https://github.com/user-attachments/assets/6acce0cc-192f-4d4d-86ff-fb56fd3c81b5)
4. So, when looking for documents representing instances of the `WorkflowExecution` class, refscan will not necessary check the same collection as those that can contain instance of the `DataGeneration` class.

Hi @aclum, here's my explanation for why refscan is reporting a violation here. Does this make sense to you?

**Comment by aclum** [comment]
The documentation doesn't show the range in that table if the range is specified in any_of. If you look at the slot itself it shows up properly
https://microbiomedata.github.io/nmdc-schema/was_generated_by/
![Screenshot 2024-10-10 at 2 36 25 PM](https://github.com/user-attachments/assets/96bc7095-51b9-44b8-a457-26f74f3ed183)

With the legacy schema WorkflowExecution (formerly WorkflowExecutionActivity) and DataGeneration (formerly OmicsProcessing) didn't share a parent, they do now.  Also I thought any_of overwrote range such that it didn't matter what was there instead of it needing to be a common ancestor. The way the documentation show on the slot page it is 'Range: [WorkflowExecution](https://microbiomedata.github.io/nmdc-schema/WorkflowExecution/) or 
[WorkflowExecution](https://microbiomedata.github.io/nmdc-schema/WorkflowExecution/) or 
[DataGeneration](https://microbiomedata.github.io/nmdc-schema/DataGeneration/)'. It is a string of OR statements which typically means if any one of the statements is true any of them are. That is still my understanding of how this should work @sierra-moxon  to confirm even though best practice is to use a common parent. If that is not the case then linkml should error saying when using any_of range values that don't have a common parent.

**Comment by sierra-moxon** [comment]
This may be too in the weeds here - I just wanted to get my thoughts documented (I can move it to LinkML if it is too much)

" _Also I thought any_of overwrote range such that it didn't matter what was there instead of it needing to be a common ancestor._ "

LinkML considers `any_of` range constraints to be **_additive_** to any existing ranges specified in slot definitions (either outside of a class's context or in the slot_usage of a slot within a class). So, given this (albeit terrible :)) example schema:

```
slots:
  drives:
     range: NamedThing
   id:
     range: integer
   type:
     range: uriorcurie


classes: 
  NamedThing:
     slots:
         - id
         - type
  Car:
    is_a: NamedThing
  Bus:
    is_a: NamedThing
  Train: 
    is_a: NamedThing

  Person:
     slots:
         - drives
     slot_usage
       drives:
          range: Car
 
  BusDriver:
     slots:
         - drives
     slot_usage
       drives:
          any_of: 
               - range: Car
               - range: Bus
```  

we want this to validate is that:
 - any instance of _BusDriver_ must drive something that is a (_NamedThing_) **AND** a (_Car_ **OR** _Bus_)

Doing a validation here could/should be stepwise, given the data:

```
- id: bd1
   drives: Train
   type: Test:BusDriver
```

validation should check:
- **test one**: bd1 is of type BusDriver, so the `drives` value should be either `NamedThing` or a descendent of `NamedThing`  ✅ this validates.
- **test two**: AND because bd1 is of type BusDriver, the `drives` value passes test one above, and because BusDriver specifies an `any_of` constraint in its `slot_usage` we must also check that the bd1 `drives` value is _additionally_ of type `Bus` or `Car.` ❌ 
   - this should produce an error report for this data. 

LinkML does not currently allow adding the code equivalent of "parenthesis" around (Bus or Car).  Instead, it checks that the `drives` value is a (`Bus,` `Car,` or `NamedThing`) because LinkML makes `any_of` range constraints additive. 

The PRs I put into LinkML makes the metamodel component `range_expression` hold the equivalent of `(Bus or Car)` so that code we write in NMDC has a way to check for `NamedThing` and `(Bus or Car)`, but they introduce some additional complexity that I won't make this post even longer with. 

Getting back to the NMDC specific issue here: 

This LinkML snippet is redundant and a bit confusing.  However, given the redundancy, it is displayed in the doc how I would expect.
```
range: WorkflowExecution
any_of:
- range: WorkflowExecution
- range: DataGeneration
```

Diving a little deeper into what the range for this _should_ be with our conversations about reducing our dependence on `any_of` in range constraints because of the LinkML issue above:

- the shared parent of `WorkflowExectuion` and `DataGenration` is `PlannedProcess`

The challenge in making `PlannedProcess` that the range here, is that `PlannedProcess` also has a few other children and could eventually have more descendants (one of those descendants is `DataGeneration though, and changing the range to the grouping class would, as you both note, would reduce the false positives).

<img width="197" alt="Screen Shot 2024-10-11 at 8 24 35 AM" src="https://github.com/user-attachments/assets/010628dd-2b04-4815-9bfc-915d41c93b95">

We could have an additional grouping class that _just_ grouped `WorkflowExecution` and `DataGeneration` and not the rest of `PlannedProcess` descendants.  I do not know the data well enough to suggest a grouping class here that is more specific.

**Comment by aclum** [comment]
Thank you for the detailed explanation @sierra-moxon. There are no current plans to use was_generated_by to refer to ids from other classes. Mark wanted to get rid of any_of so I think grouping classes is the way to go.

**Comment by aclum** [comment]
@eecavanna up you if you want to implement the range + any_of range as additive or wait until we make the grouping classes.

**Comment by eecavanna** [comment]
I looked into this issue.

### Summary

In `linkml-runtime` version 1.8.0, the `SchemaView` class was not behaving the way I expected. In `linkml-runtime` version 1.8.3, it is. Details are below.

### Details

#### Refscan snippet

Here's how I create the `SchemaView`:

```py
    schema_view = linkml_runtime.SchemaView(schema_file_path)
```

Here's how I dump the messages below (this is temporary debug code I added while working on this issue):

```py
                    print(f"{class_name=}")
                    print(f"{slot_name=}")
                    print(f"{slot_definition.range=}")
                    print(f"{slot_definition.any_of=}")
                    for anon_slot_expression in slot_definition.any_of:
                        print(f"{anon_slot_expression=}")
                    print(f"{names_of_eligible_target_classes=}\n")
```

#### With linkml-runtime 1.8.0

When using `linkml-runtime` version 1.8.0, the `any_of` list was empty: 🔴 

```py
class_name='DataObject'
slot_name='was_generated_by'
slot_definition.range='WorkflowExecution'
slot_definition.any_of=[]
names_of_eligible_target_classes=['MetagenomeSequencing', 'ReadQcAnalysis', 'MetagenomeAnnotation', 'MetabolomicsAnalysis', 'MetatranscriptomeExpressionAnalysis', 'MetaproteomicsAnalysis', 'MagsAnalysis', 'MetatranscriptomeAnnotation', 'NomAnalysis', 'ReadBasedTaxonomyAnalysis', 'MetagenomeAssembly', 'MetatranscriptomeAssembly', 'WorkflowExecution']
```

Given that, it does not surprise me that refscan did not consider a `DataGeneration` instance to be a possible target of a `DataObject.was_generated_by` reference.

#### With linkml-runtime 1.8.3

When I updated `linkml-runtime` to version 1.8.3 just now and re-ran refscan, the `slot_definition.any_of` list was **non-empty**: 🟢 

```py
class_name='DataObject'
slot_name='was_generated_by'
slot_definition.range='WorkflowExecution'
slot_definition.any_of=[AnonymousSlotExpression({'range': 'WorkflowExecution'}), AnonymousSlotExpression({'range': 'DataGeneration'})]
anon_slot_expression=AnonymousSlotExpression({'range': 'WorkflowExecution'})
anon_slot_expression=AnonymousSlotExpression({'range': 'DataGeneration'})
names_of_eligible_target_classes=['NucleotideSequencing', 'MassSpectrometry', 'MetagenomeAnnotation', 'ReadQcAnalysis', 'MetatranscriptomeAnnotation', 'WorkflowExecution', 'MetatranscriptomeExpressionAnalysis', 'MagsAnalysis', 'MetabolomicsAnalysis', 'MetagenomeAssembly', 'MetatranscriptomeAssembly', 'MetagenomeSequencing', 'NomAnalysis', 'ReadBasedTaxonomyAnalysis', 'MetaproteomicsAnalysis', 'DataGeneration']
```

Given that, I do expect refscan—when using that newer `link-runtime` version—to consider a `DataGeneration` instance to be a possible target of a `DataObject.was_generated_by` reference.

I will update that dependency in refscan and release a new version of refscan.

**Comment by eecavanna** [comment]
**Confirmed:** Refscan version `0.1.22` reports 0 violations in the `data_object_set` collection (using `nmdc-schema` version `11.0.3` and the production database).

Here's a screenshot of refscan's console output in that situation:

![image](https://github.com/user-attachments/assets/8ea209d2-24b2-4123-8e1f-b76d03ccc074)

In addition, I confirmed the `references.tsv` file generated by refscan lists the `data_generation_set` collection as an eligible home for the documents being referenced by `DataObject.was_generated_by`.

![image](https://github.com/user-attachments/assets/10023556-bfaf-47fe-8fdb-b6fb98421ace)

Closing as fixed.

**Comment by eecavanna** [comment]
One more screenshot to go along with my previous comment. Here's an inter-collection relationship diagram (generated using the new version of refscan; i.e. version `0.1.22`), which shows that documents in the `data_object_set` collection can, indeed, contain references to documents in the `data_generation_set` collection.

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/e7c2db1a-77a2-4992-af7a-03d2b3de4917">
